services:
  db:
    image: mysql:8.0
    restart: always
    container_name: sample_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # docker起動時にDBに対して実行したいクエリ

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    container_name: sample_myadmin
    environment:
      - PMA_HOSTS=sample_db
    depends_on:
      - db
    ports:
      - '8000:80'